export type TrackObject = {
album?: ;
artists?: ;
available_markets?: ;
disc_number?: Number;
duration_ms?: Number;
explicit?: Boolean;
external_ids?: ;
external_urls?: ;
href?: String;
id?: String;
is_playable?: Boolean;
linked_from?: ;
restrictions?: ;
name?: String;
popularity?: Number;
preview_url?: String;
track_number?: Number;
type?: String;
uri?: String;
is_local?: Boolean;
};